### ISSUE TITLE
Error when join in my server after update server launcher

### ISSUE THREAD

**Issue by Svenhr** [NicholasSchmitz/altV-gangwar-server#2]
[22:02:47][Error] [V8] Exception at altv-gangwar:file:///C:/altv-server/resources/altv-gangwar/server/util/functions.mjs:194
[22:02:47][Error]           let player1TeamColor = player1.getMeta('team') !== null ? teamData[playe...
[22:02:47][Error]   TypeError: Cannot read property 'colors' of undefined
    at addToKillFeed (file:///C:/altv-server/resources/altv-gangwar/server/util/functions.mjs:194:101)
    at handlePlayerConnect (file:///C:/altv-server/resources/altv-gangwar/server/spawn/spawn.mjs:22:5)
[22:02:47][Warning] Event handler at altv-gangwar:file:///C:/altv-server/resources/altv-gangwar/server/spawn/spawn.mjs:9 was too long 69ms
[22:02:48][Warning] resourceManager.Update() took: 63 ms
[22:03:18][Error] [V8] Exception at altv-gangwar:file:///C:/altv-server/resources/altv-gangwar/server/util/functions.mjs:194
[22:03:18][Error]           let player1TeamColor = player1.getMeta('team') !== null ? teamData[playe...
[22:03:18][Error]   TypeError: Cannot read property 'colors' of undefined
    at addToKillFeed (file:///C:/altv-server/resources/altv-gangwar/server/util/functions.mjs:194:101)
    at handlePlayerConnect (file:///C:/altv-server/resources/altv-gangwar/server/spawn/spawn.mjs:22:5)
[22:03:18][Warning] Event handler at altv-gangwar:file:///C:/altv-server/resources/altv-gangwar/server/spawn/spawn.mjs:9 was too long 60ms
[22:03:30][Error] [V8] Exception at altv-gangwar:file:///C:/altv-server/resources/altv-gangwar/server/util/functions.mjs:194
[22:03:30][Error]           let player1TeamColor = player1.getMeta('team') !== null ? teamData[playe...
[22:03:30][Error]   TypeError: Cannot read property 'colors' of undefined
    at addToKillFeed (file:///C:/altv-server/resources/altv-gangwar/server/util/functions.mjs:194:101)
    at handlePlayerConnect (file:///C:/altv-server/resources/altv-gangwar/server/spawn/spawn.mjs:22:5)
[22:03:30][Warning] Event handler at altv-gangwar:file:///C:/altv-server/resources/altv-gangwar/server/spawn/spawn.mjs:9 was too long 37ms
[22:03:33] [Tue Feb 04 2020 22:03:33 GMT+0100 (GMT+01:00)]: TypeError: Cannot read property 'driver' of undefined
    at destroyPlayerVehicleIfNoDriver (file:///C:/altv-server/resources/altv-gangwar/server/util/functions.mjs:249:31)
    at handlePlayerDisconnect (file:///C:/altv-server/resources/altv-gangwar/server/spawn/spawn.mjs:35:5)

[22:03:33] [Tue Feb 04 2020 22:03:33 GMT+0100 (GMT+01:00)]: TypeError: Cannot read property 'driver' of undefined
    at destroyPlayerVehicleIfNoDriver (file:///C:/altv-server/resources/altv-gangwar/server/util/functions.mjs:257:30)
    at handlePlayerDisconnect (file:///C:/altv-server/resources/altv-gangwar/server/spawn/spawn.mjs:35:5)

**Comment by Svenhr** [comment]
And im stuck in loadingscreen

**Comment by NicholasSchmitz** [comment]
That's because of the alt:V server update. I'm not sure if i'll fix it in the future. If I do so, I will tell you.
