### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thug-thug** [NicholasSchmitz/altV-gangwar-server#3]
[22:52:15][Error] [V8] Exception at altV-gangwar:file:///C:/Users/Carlos/Desktop/altv-server/resources/altV-gangwar/server/util/functions.mjs:194
[22:52:15][Error]           let player1TeamColor = player1.getMeta('team') !== null ? teamData[playe...
[22:52:15][Error]   TypeError: Cannot read property 'colors' of undefined
    at addToKillFeed (file:///C:/Users/Carlos/Desktop/altv-server/resources/altV-gangwar/server/util/functions.mjs:194:101)
    at handlePlayerConnect (file:///C:/Users/Carlos/Desktop/altv-server/resources/altV-gangwar/server/spawn/spawn.mjs:22:5)

i cant acess server

**Comment by NicholasSchmitz** [comment]
That's because of the alt:V server update. I'm not sure if i'll fix it in the future. If I do so, I will tell you.
