### ISSUE TITLE
TypeError: Cannot read property 'colors' of undefined

### ISSUE THREAD

**Issue by Sevage** [NicholasSchmitz/altV-gangwar-server#5]
Hi, beschäftigst du dich noch mit dem Script?
Bin heute darauf gestoßen und erhalten folgenden Fehler nach dem Start:

[17:23:18][Error] [V8] Exception at altv-gangwar:file:///***/resources/altv-gangwar/server/util/functions.mjs:211
[17:23:18][Error]                   ? teamData[player1.getMeta('team')].colors.hex
[17:23:18][Error]   TypeError: Cannot read property 'colors' of undefined
    at addToKillFeed (file:///***/resources/altv-gangwar/server/util/functions.mjs:211:53)
    at handlePlayerConnect (file:///***/resources/altv-gangwar/server/spawn/spawn.mjs:38:5)

Grüße

**Comment by NicholasSchmitz** [comment]
Leider kein Support mehr.
