### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by SupperCraft5000** [NicholasSchmitz/altV-gangwar-server#6]
```
[20:30:20] alt:V Server, build #1181, branch release
[20:30:20] Starting alt:V Server on 0.0.0.0:7788
[20:30:20] Loading resource gangwar
[20:30:20] Error: ENOENT: no such file or directory, open 'G:\resources\altv-gangwar\error.txt'
[20:30:20] Error: ENOENT: no such file or directory, open 'G:\resources\altv-gangwar\error.txt'
[20:30:20] Loaded resource gangwar
[20:30:20] Starting HTTP server on 0.0.0.0:7788
[20:30:20] Server started
```

**Comment by NicholasSchmitz** [comment]
Send content of G:\resources\altv-gangwar\error.txt

**Comment by SupperCraft5000** [comment]
Fixt hat error by renaming my resource to altv-gangwar.
But i become a other error now

```
[20:36:25] alt:V Server, build #1181, branch release
[20:36:25] Starting alt:V Server on 0.0.0.0:7788
[20:36:25] Loading resource altv-gangwar
[20:36:25] Loaded resource altv-gangwar
[20:36:25] Starting HTTP server on 0.0.0.0:7788
[20:36:26] Server started
[20:36:30][Error] [V8] Exception at altv-gangwar:file:///G:/testserver/resources/altv-gangwar/server/util/functions.mjs:194
[20:36:30][Error]           let player1TeamColor = player1.getMeta('team') !== null ? teamData[playe...
[20:36:30][Error]   TypeError: Cannot read property 'colors' of undefined
    at addToKillFeed (file:///G:/testserver/resources/altv-gangwar/server/util/functions.mjs:194:101)
    at handlePlayerConnect (file:///G:/testserver/resources/altv-gangwar/server/spawn/spawn.mjs:22:5)
[20:36:30][Warning] Event handler at altv-gangwar:file:///G:/testserver/resources/altv-gangwar/server/spawn/spawn.mjs:9 was too long 7ms
```
